### ISSUE TITLE
Scrollbar hides flux:select variant="listbox"

### ISSUE THREAD

**Issue by beneyraheem** [livewire/flux#1377]
### Flux version

v2.1.1

### Livewire version

v3.6.2

### Tailwind version

v4.0.15

### Browser and Operating System

Chrome

### What is the problem?

https://github.com/user-attachments/assets/a430b1cd-69c7-4079-9d4c-9eb476318357

Main scrollbar hides when open.

### Code snippets

```
<flux:select variant="listbox" placeholder="Choose industry...">
    <flux:select.option>Photography</flux:select.option>
    <flux:select.option>Design services</flux:select.option>
    <flux:select.option>Web development</flux:select.option>
    <flux:select.option>Accounting</flux:select.option>
    <flux:select.option>Legal services</flux:select.option>
    <flux:select.option>Consulting</flux:select.option>
    <flux:select.option>Other</flux:select.option>
</flux:select>
```

### How do you expect it to work?

Main scrollbar should not hide, when it does, there is a starange UI change.

### Please confirm (incomplete submissions will not be addressed)

- [x] I have provided easy and step-by-step instructions to reproduce the bug.
- [x] I have provided code samples as text and NOT images.
- [x] I understand my bug report will be closed if I haven't met the criteria above.

**Comment by joshhanley** [comment]
@beneyraheem thanks for reporting! Flux locks background scroll when the select is open, which is why the scroll bar disappears. This is by design. Currently there is no way to disable background scroll without the scroll bar disappearing, so I'm going to close this issue.

**Comment by ju5t** [comment]
@joshhanley this causes unwanted layout shifts. In modals for example you see the entire background shift, which isn't pretty. I understand this is a side-effect of locking background scrolling, but I hope this is something that can be solved differently.

https://github.com/user-attachments/assets/ac31c8dd-67c4-44e3-aa30-c6ff39fd7bfd

**Comment by joshhanley** [comment]
@ju5t yep that's a known issue, see #1461. It has been fixed, just waiting to be merged.

**Comment by ju5t** [comment]
@joshhanley ah thanks, that's great! I somehow missed that when searching if it had been fixed yet.

**Comment by beneyraheem** [comment]
It still does not fix in my layout, yeah there is no background shift, but it add white scroll area, and add this style to head tag

style="padding-right: calc(15px); overflow: hidden;"

which hides default scrollbar and add white bar, not great for layout

![Image](https://github.com/user-attachments/assets/1eaaf414-0ca7-473f-b7af-b04a81a44feb)
