### ISSUE TITLE
Context menu only works on firefox when used with a mac trackpad

### ISSUE THREAD

**Issue by benshawuk** [livewire/flux#22]
When contextually clicking (control click) on MacOS with Safari and Chrome, the menu instantly disappears.
However, it works when right clicking with a mouse.
If you keep the trackpad button pressed down, the menu stays, but disappears as soon as you let go.
On firefox it seems to behave correctly.

**Comment by rzv-me** [comment]
The problem is in the context menu JS code.

there is a check to dismiss the context menu if the click was not a right click, but it should also check for ctrl+left click
fix:
```javascript
        if (e.button !== 2 && !(e.button === 0 && e.ctrlKey === true)) return;
```
or
```javascript
        let isRightClick = e.button === 2;
        let isCtrlClick = e.button === 0 && e.ctrlKey === true;
        if (!isRightClick && !isCtrlClick) return;
``` 
but this is something that I can't fix, only @calebporzio can

**Comment by calebporzio** [comment]
I think the actual problem has to do with the `[popover]` attribute and it's light dismissal behavior.

when doing "ctrl+click", it opens on mousedown properly, but the mouseup triggers a "light dismissal" for the `[popover` element.

There is currently no easy way around this. I will look into a new popover strategy, maybe using manual popovers for everything and manually handling light dismissal so we can make exceptions for cases like this.

Thanks for the report.

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.

**Comment by timgavin** [comment]
I'm still seeing this issue [in the docs](https://fluxui.dev/components/context). Using Safari with a trackpad.
