### ISSUE TITLE
Radio Group does not show selected when values are intergers

### ISSUE THREAD

**Issue by roadsend** [livewire/flux#227]
** This will display checked on 3 resources **
    public string $resourceCount = '3';   // has to be a string to load value in radio group

    public function mount()
    {
        $this->resourceCount = (string) 3;
     
   <flux:radio.group  wire:model="resourceCount" label="How Many Resources Displayed">
        <flux:radio value="3" label="3 Resources"/>
        <flux:radio value="6" label="6 Resources"/>
        <flux:radio value="9" label="9 Resources"/>
    </flux:radio.group>

** This shows no selected value **
    public int $resourceCount = 3;   // making this an int prevents current value from display
    public function mount()
    {
        $this->resourceCount = 3;
     
   <flux:radio.group  wire:model="resourceCount" label="How Many Resources Displayed">
        <flux:radio value=3 label="3 Resources"/>
        <flux:radio value=6 label="6 Resources"/>
        <flux:radio value=9 label="9 Resources"/>
    </flux:radio.group>

**Comment by ju5t** [comment]
This doesn't work in selects either. It's more a 'Livewire' issue than it is a 'Flux' issue though as I think it's related to `wire:model`. 

I have no idea how this works in either case, both radio and selects. But either a less strict comparison would help, or if that's not possible, just cast everything to a string instead underneath.

**Comment by helderneves91** [comment]
Could this be related to https://github.com/livewire/flux/issues/260

**Comment by ju5t** [comment]
@helderneves91 yes, it's the same issue.

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.

**Comment by achatzi78** [comment]
Sorry to bump a closed issue, but I have the latest Flux version (1.0.29) and the latest Livewire version (3.5.16) and it is still not working for me.

This is a Volt component for testing
```php
use Livewire\Volt\Component;
 
new class extends Component {
    public ?bool $is_active = null;

    publc function save() {}
} ?>
 <form wire:submit="save">
    <flux:radio.group wire:model="is_active" label="{{ Str::title(__('active')) }}" class="flex gap-4 *:gap-x-2 required">
        <flux:radio value="1" label="{{ Str::title('yes') }}" />
        <flux:radio value="0" label="{{ Str::title('no') }}" />
    </flux:radio.group>

    <flux:button type="submit" variant="primary" icon="check">Submit</flux:button>
</form>
```

I check the yes option and when I when I submit the form it resets and is not displayed as checked.  The only way to make this work is if I declare the is_active property as string `public ?string $is_active = null;`

**Comment by joshhanley** [comment]
@achatzi78 thanks for reporting!

I just tested this and the issue is the `bool` type hint. Due to it being a `bool`, Livewire is taking the values (1 or 0) and converting them to a boolean. What that means is that then the value is `true` or `false` which doesn't match `1` or `0` hence the checked radio is being cleared.

I think it would be best to actually use an `int` type hint when the values are integers, like this:

```blade
<?php

use Livewire\Volt\Component;

new class extends Component {
    public ?int $is_active = null;

    public function save()
    {
        dump($this->is_active);
    }
}; ?>

<form wire:submit="save">
    <flux:radio.group wire:model="is_active" label="{{ Str::title(__('active')) }}" class="flex gap-4 *:gap-x-2 required">
        <flux:radio value="1" label="{{ Str::title('yes') }}" />
        <flux:radio value="0" label="{{ Str::title('no') }}" />
    </flux:radio.group>

    <flux:button type="submit" variant="primary" icon="check">Submit</flux:button>
</form>
```

**Comment by achatzi78** [comment]
@joshhanley Thanks Josh.  I tried it and yes it does work as you say.  But to me it should be able to work with boolean as well, I have a project built with Livewire and Tailwind and I am converting it to Flux, so the code was working when I had regular radio inputs.

In any case, this is a small matter, it is not a problem changing the bool to int, just something to keep in mind when your team has time to address it.

Thanks again.
