### ISSUE TITLE
Issue with Toast and Redirect Using navigate to the Same Route

### ISSUE THREAD

**Issue by gustavosobrinho01** [livewire/flux#379]
I am encountering an issue when using Flux with navigate to redirect to the same route. When I click the button, Flux triggers correctly the first time, but on the second attempt, it no longer works, and no further redirection occurs.

It seems that the expected redirection behavior is being interrupted when navigating to the same route. The problem manifests after the first successful interaction.

**Comment by jeffchown** [comment]
@gustavosobrinho01 Can you provide a code example?

**Comment by gustavosobrinho01** [comment]
```
public function toast()
{
    Flux::toast('I clicked the toast!', variant: 'success');

    $this->redirectRoute('dashboard', navigate: true);
}

<flux:button wire:click="toast" class="m-5">Show toast</flux:button>

On the first click, it displays the toast, but on the second click, it no longer shows.

**Comment by jeffchown** [comment]
Thanks, @gustavosobrinho01 .  When I try your code in my Flux test app, I can click the `Show toast` button multiple times with each click successfully redirecting to the same page (per the dev tools network tab).

NOTE: In my case, however, the toast is not displayed on any of the button clicks (I assume this is because the redirect happens too quickly thus negating the toast's display)

**Comment by jeffchown** [comment]
Not sure if this applies or might help, but there has been discussion of adding 'flash-like' functionality to toast: https://github.com/livewire/flux/discussions/139

**Comment by gustavosobrinho01** [comment]
According to the Flux documentation, when using persist, it should work normally. Shouldn’t it?

**Comment by gustavosobrinho01** [comment]
Even after following what this issue suggests, it still doesn’t work. Feel free to test it yourself if you’d like.

**Comment by jeffchown** [comment]
> According to the Flux documentation, when using persist, it should work normally. Shouldn’t it?

Yes, according to the documentation it should, but it doesn't for me when I just tested it.

**Comment by dudelisius** [comment]
I ran into the same issue as well. This was resolved however by using `$this->redirect(route('dashboard), true);` instead of using `redirectRoute`.

**Comment by jeffchown** [comment]
> I ran into the same issue as well but I was able to resolve/fix this by using `$this->redirect(route('dashboard), true);` instead of using `redirectRoute`.

Thanks @dudelisius , unfortunately, that didn't fix it for me.

**Comment by gustavosobrinho01** [comment]
> I ran into the same issue as well but I was able to resolve/fix this by using `$this->redirect(route('dashboard), true);` instead of using `redirectRoute`.

For me, it doesn’t work either.

**Comment by calebporzio** [comment]
This has been fixed in Livewire:

https://github.com/livewire/livewire/releases/tag/v3.5.10

**Comment by jeffchown** [comment]
Nice!  Tested and works now in both my apps.  Thanks, @calebporzio !

**Comment by gustavosobrinho01** [comment]
Nice!!! Thanks, @calebporzio !
