### ISSUE TITLE
Select variant="combobox" not showing selected value when loaded

### ISSUE THREAD

**Issue by ptravassos** [livewire/flux#526]
```
<?php
use Livewire\Volt\Component;
use Illuminate\Support\Collection;

new class extends Component {
    public $supplier_id = "A";
}; ?>

<div class="w-96">
    <flux:select variant="combobox" wire:model="supplier_id" size="sm" placeholder="Select a supplier" label="Supplier">
            <flux:option wire:key="test-1" value="A">Value A</flux:option>
            <flux:option wire:key="test-2" value="B">Value B</flux:option>
    </flux:select>
</div>
```

When component is loaded it doesn't show the selected value:
![Image](https://github.com/user-attachments/assets/c70f2506-0b97-4662-bc92-7ed55b72fb7d)

If i open de selectbox it is actually selected:
![Image](https://github.com/user-attachments/assets/6334d6f1-f669-4787-88e6-30925580bba6)

And if a click out to close it, now it shows the selected value:
![Image](https://github.com/user-attachments/assets/b57878b1-eb08-4f90-ac62-e4aa84fe7e73)

Thank you!

**Comment by joshhanley** [comment]
@ptravassos I believe this was already fixed.

Can you please confirm what Livewire and Flux versions you are currently on by running 'composer show -D' in your console and sharing exact version numbers?

Make sure they are both in the latest version Livewire v3.5.12 and Flux v1.0.17. Make sure you also clear your view cache using 'php artisan view:clear'.

**Comment by ptravassos** [comment]
I run optimize:clear regularly, and updated flux a few moments ago, the beahavior is still the same.
The code is on the first comment (i edit it, was not formatted correctly)

1: php artisan view:clear
2: composer show -D
```
barryvdh/laravel-debugbar      3.14.3  PHP Debugbar integration for Laravel
fakerphp/faker                 1.23.1  Faker is a PHP library that generates fake dat...
lab404/laravel-impersonate     1.7.5   Laravel Impersonate is a plugin that allows to...
laravel/breeze                 2.2.2   Minimal Laravel authentication scaffolding wit...
laravel/framework              11.28.0 The Laravel Framework.
laravel/pint                   1.18.1  An opinionated code formatter for PHP.
laravel/sail                   1.36.0  Docker files for running a basic Laravel appli...
laravel/tinker                 2.10.0  Powerful REPL for the Laravel framework.
livewire/flux                  1.0.17  The official UI component library for Livewire.
livewire/flux-pro              1.0.17  The pro version of Flux, the official UI compo...
livewire/livewire              3.5.12  A front-end framework for Laravel.
livewire/volt                  1.6.5   An elegantly crafted functional API for Larave...
mockery/mockery                1.6.12  Mockery is a simple yet flexible PHP mock obje...
nunomaduro/collision           8.5.0   Cli error handling for console/command-line PH...
pestphp/pest                   3.4.1   The elegant PHP Testing Framework.
pestphp/pest-plugin-laravel    3.0.0   The Pest Laravel Plugin
spatie/laravel-ignition        2.8.0   A beautiful error page for Laravel applications.
spatie/laravel-permission      6.9.0   Permission handling for Laravel 8.0 and up
```

**Comment by calebporzio** [comment]
I can confirm this is a bug. The provided code snippet breaks. The fix from before only applies to the listbox. The combobox "selected" value is a separate system because it's in the input field directly. Will investigate.
