### ISSUE TITLE
Accordion Backspace or Cut

### ISSUE THREAD

**Issue by eneadrian** [livewire/flux#65]
If you delete (or cut ctrl+x) all text from an input the accordion automatically closes

https://github.com/user-attachments/assets/f6544943-ba6e-4591-8466-68fb8dd36080

**Comment by jeffchown** [comment]
Exact same thing happens with (forms in) modals

**Comment by jeffchown** [comment]
Anyone have a temporary workaround for this?

**Comment by jeffchown** [comment]
No worries :) @eneadrian

**Comment by calebporzio** [comment]
Thank you for the report. This issue has been fixed and will be available in the next release.

**Comment by jeffchown** [comment]
Hi @calebporzio - I just applied Flux/Flux-pro 1.0.7 to my two projects that were experiencing this issue.

Unfortunately, they both still have the same issue.  I cleared all caches (in Laravel and browser) and recompiled/rebuilt all assets to no avail.  In each case, the accordion still closes per the original post.

Any ideas?

**Comment by jeffchown** [comment]
@calebporzio Please ignore my previous, all is good.  I had to republish the Flux components in my apps. 🤦‍♂️
