### ISSUE TITLE
Cannot use wire:model on <flux:autocomplete>

### ISSUE THREAD

**Issue by jtesta66** [livewire/flux#74]
I encountered this issue while trying to set up a "day of week" autocomplete. 

I tried simplifying my component's blade file so it was just an autocomplete (so I could rule out anything else), and the following code sample threw the same error.

```
<div>
    <flux:autocomplete wire:model="state_sales_tax" label="State Sales Tax Rate (%)">
        <flux:autocomplete.item>1</flux:autocomplete.item>
        <flux:autocomplete.item>2</flux:autocomplete.item>
        <flux:autocomplete.item>3</flux:autocomplete.item>
        <flux:autocomplete.item>4</flux:autocomplete.item>
        <flux:autocomplete.item>5</flux:autocomplete.item>
        <flux:autocomplete.item>6</flux:autocomplete.item>
        <flux:autocomplete.item>7</flux:autocomplete.item>
        <flux:autocomplete.item>8</flux:autocomplete.item>
        <flux:autocomplete.item>9</flux:autocomplete.item>
        <flux:autocomplete.item>10</flux:autocomplete.item>
    </flux:autocomplete>
</div>
```

My original autocomplete was this, and it was inside a form, etc.  Originally, I was using "wire:model.blur" but removed that to see if it made a difference, and it didn't.

```
<div class="grid grid-cols-2 gap-4">
    <flux:autocomplete wire:model="invoices_schedule_day" label="Day Invoices are Generated">
        <flux:autocomplete.item>Sunday</flux:autocomplete.item>
        <flux:autocomplete.item>Monday</flux:autocomplete.item>
        <flux:autocomplete.item>Tuesday</flux:autocomplete.item>
        <flux:autocomplete.item>Wednesday</flux:autocomplete.item>
        <flux:autocomplete.item>Thursday</flux:autocomplete.item>
        <flux:autocomplete.item>Friday</flux:autocomplete.item>
        <flux:autocomplete.item>Saturday</flux:autocomplete.item>
    </flux:autocomplete>
</div>
```

**Comment by idealerror** [comment]
Duplicate of https://github.com/livewire/flux/issues/17.  It's being fixed in the private repo

**Comment by joshhanley** [comment]
@jtesta66 closing this as it has been fixed in v1.0.1, so please update.

**Comment by jtesta66** [comment]
@joshhanley I had updated to 1.0.1 earlier today, and it was still broken.  However, I must have had something I cached; I cleared all the various caches, and it seems to work now. Thank you.
